
services:
  dofus-db:
    image: mongo:latest
    container_name: dofus-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"

volumes:
  mongo_data:
